config/routes.rb
Solar::Application.routes.draw do 

  devise_for :users, :path_names => {:sign_up => :register}

  devise_scope :user do
    get  :login, to: "devise/sessions#new"
    post :login, to: "devise/sessions#create"
    get  :logout, to: "devise/sessions#destroy"
    get "/", to: "devise/sessions#new"
    resources :sessions, only: [:create]
  end

  ## users/:id/photo
  ## users/edit_photo
  resources :users do
    get :photo, on: :member
    put :update_photo, on: :member
    get :edit_photo, on: :collection
    get :verify_cpf, on: :collection
  end

  resources :social_networks, only: [] do
    collection do
      get :fb_authenticate
      get :fb_feed
      get :fb_logout
      get :fb_post_wall
    end
  end

  ## curriculum_units/:id/participants
  ## curriculum_units/:id/informations
  resources :curriculum_units do
    collection do 
      get :list
      get :mobilis_list
      get :list_informations
      get :list_participants
      get :list_combobox, to: :index, combobox: true, as: :list_combobox
    end
    member do
      get :participants
      get :informations
      get :home
    end
    resources :groups, only: [:index] do
      collection do 
        get :mobilis_list
      end
    end
  end

  ## groups/:id/discussions
  resources :groups, except: [:show] do
    resources :discussions, only: [:index] do
      collection do 
        get :mobilis_list
      end
    end  
    get :list, on: :collection
    get :list_to_edit, to: :list, on: :collection, edition: true
    get :academic_index, on: :collection
    put :unbind, on: :member, to: :change_tool, type: "unbind"
    put :remove, on: :member, to: :change_tool, type: "remove"
    put :add, on: :collection, to: :change_tool, type: "add"
  end

  ## discussions/:id/posts
  resources :discussions do
    get :list, on: :collection
    resources :posts, except: [:show, :new, :edit] do
      collection do
        get "user/:user_id", to: :show, as: :user
        get ":type/:date(/order/:order(/limit/:limit))", to: :index, defaults: {display_mode: 'list'} # :types => [:news, :history]; :order => [:asc, :desc]
      end
    end
  end

  ## posts/:id/post_files
  resources :posts, only: [:index] do
    resources :post_files, only: [:new, :create, :destroy, :download] do
      get :download, on: :member
    end
  end

  ## allocations/enrollments
  resources :allocations, except: [:new] do
    collection do
      get :designates
      get :enrollments, action: :index
      get :search_users
      post :create_designation
    end
    member do
      delete :cancel, action: :destroy
      delete :cancel_request, action: :destroy, defaults: {type: 'request'}

      post :reactivate
      put :deactivate
      put :activate
    end
  end

  resources :semesters, except: [:show] do
    get :list_combobox, to: :index, combobox: true, as: :list_combobox, on: :collection
    resources :offers, only: [:index, :new]
  end

  resources :offers, except: [:new] do
    post :deactivate_groups, on: :member
    get :list, on: :collection
  end

  resources :scores, only: [:index, :show] do
    collection do 
    get "student/:student_id", action: :show, as: :student
    get :amount_history_access
    get "history_access/:id", action: :history_access
    end
    get :history_access, on: :member
  end

  resources :enrollments, only: :index
  resources :courses do 
    get :list_combobox, to: :index, combobox: true, as: :list_combobox, on: :collection
  end

  resources :editions, only: [] do
    collection do
      get :items
      get :academic
      get :content
      get "academic/:curriculum_unit_type_id/courses", to: "editions#courses", as: :academic_courses
      get "academic/:curriculum_unit_type_id/curriculum_units", to: "editions#curriculum_units", as: :academic_uc
      get "academic/:curriculum_unit_type_id/semesters", to: "editions#semesters", as: :academic_semesters
      get "academic/:curriculum_unit_type_id/groups", to: "editions#groups", as: :academic_groups
    end
  end

  resources :lessons do
    member do
      put "change_status/:status", to: :change_status, as: :change_status
      get :header, to: :show_header
      get :content, to: :show_content
      put "order/:change_id", action: :order, as: :change_order
      put :change_module
    end
    collection do
      get :list, action: :list
      get :download_files
      get :verify_download
    end
    resources :files, controller: :lesson_files, except: [:index, :show, :update, :create] do
      collection do
        get "extract/:file", to: :extract_files, as: :extract, constraints: { file: /.*/ }
        post :folder, to: :new, defaults: {type: 'folder'}, as: :new_folder
        post :file, to: :new, defaults: {type: 'file'}, as: :new_file
        put :rename_node, to: :edit, defaults: {type: 'rename'}
        put :move_nodes, to: :edit, defaults: {type: 'move'}
        put :upload_files, to: :new, defaults: {type: 'upload'}, as: :upload
        put :define_initial_file, to: :edit, defaults: {type: 'initial_file'}, as: :initial_file
        delete :remove_node, to: :destroy
      end
    end
  end
  get :lesson_files, to: "lesson_files#index", as: :lesson_files
 
  mount Ckeditor::Engine => "/ckeditor"

  resources :assignments do
    collection do
      get :student
      get :professor

      get :download_files
      get :send_public_files_page

      post :upload_file
      delete :delete_file
    end
    member do
      get :information
      get :import_groups_page
      post :evaluate
      post :send_comment
      post :manage_groups
      post :import_groups
      delete :remove_comment
    end
  end

  resources :chat_rooms

  resources :schedules, only: [:index] do
    get :list, on: :collection
  end

  resources :messages, except: [:destroy, :update] do
    member do
      put ":box/:new_status", to: "messages#update", as: :change_status, constraints: {box: /(inbox)|(outbox)|(trashbox)/, new_status: /(read)|(unread)|(trash)|(restore)/}
    end

    collection do
      get :index, box: "inbox"
      get :inbox, action: :index, box: "inbox", as: :inbox
      get :outbox, action: :index, box: "outbox", as: :outbox
      get :trashbox, action: :index, box: "trashbox", as: :trashbox

      post :ajax_get_contacts
      post :send_message

      get "download/file/:file_id", to: "messages#download_files", as: :download_file
    end
  end

  resources :pages, only: [:index] do
    # get :team, on: :collection
  end

  resources :lesson_modules, except: [:index, :show]

  # resources :tabs, only: [:show, :create, :destroy]
  get :activate_tab, to: "tabs#show", as: :activate_tab
  get :add_tab, to: "tabs#create", as: :add_tab
  get :close_tab, to: "tabs#destroy", as: :close_tab

  get :home, to: "users#mysolar", as: :home
  get :user_root, to: 'users#mysolar'

  resources :support_material_files do
    get :download, on: :member
    collection do
      get :list
      get "at/:allocation_tag_id/download", to: :download, type: :all, as: :download_all
      get "at/:allocation_tag_id/folder/:folder/download", to: :download, type: :folder, as: :download_folder
      get "at/download", to: :download, type: :all, as: :download_all
      get "at/folder/:folder/download", to: :download, type: :folder, as: :download_folder
    end
  end

  get "bibliography/list", to: "bibliography#list"

  get "/media/lessons/:id/:file.:extension", to: "access_control#lesson", index: true
  get "/media/lessons/:id/:folder/*path", to: "access_control#lesson", index: false

  get "/media/users/:user_id/photos/:style.:extension", to: "access_control#users"

  get "/media/messages/:file.:extension", to: "access_control#message"
  get "/media/assignment/sent_assignment_files/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/comments/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/public_area/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/enunciation/:file.:extension", to: "access_control#assignment"

  # IM
  resources :instant_messages, only: [] do
    collection do
      get :register_user
      get :prebind
    end
  end

  root to: 'devise/sessions#new'

  # match ':controller(/:action(/:id(.:format)))'
end

app/models/curriculum_unit_type.rb
class CurriculumUnitType < ActiveRecord::Base
  has_many :curriculum_units
end

app/helpers/curriculum_units_helper.rb
module CurriculumUnitsHelper

  def message_class_participants (user_id, curriculum_unit, profile_flag, have_profile = true, offer_id = nil, group_id = nil)
    if curriculum_unit
      allocation_tag_id = AllocationTag.find_by_group_id(curriculum_unit).id

      # allocation_tag_id será a de unidade curricular se houver allocation para o usuário
      if Allocation.find_by_user_id_and_allocation_tag_id(user_id, allocation_tag_id).nil?
        if offer_id
          allocation_tag_id = AllocationTag.find_by_group_id(offer_id).id

          # allocation_tag_id será a de oferta se houver allocation para o usuário
          if Allocation.find_by_user_id_and_allocation_tag_id(user_id, allocation_tag_id).nil?
            if group_id
              allocation_tag_id = AllocationTag.find_by_group_id(group_id).id
            end
          end
        elsif group_id # Caso oferta seja nil
          allocation_tag_id = AllocationTag.find_by_group_id(group_id).id
        end
      end

      negative = have_profile ? '' : 'NOT'
      query = "
            SELECT DISTINCT
              users.id, users.name as username, users.photo_file_name, users.email, p.name as profilename, p.id as profileid
            FROM
              allocations al
              inner join profiles p on al.profile_id = p.id
              INNER JOIN users  ON al.user_id = users.id
              inner join
              (select
                     root.id as allocation_tag_id,
                     CASE
                       WHEN group_id is not null THEN (select 'GROUP'::text)
                       WHEN offer_id is not null THEN (select 'OFFER'::text)
                       WHEN course_id is not null THEN (select 'COURSE'::text)
                       ELSE (select 'CURRICULUM_UNIT'::text)
                     END as entity_type,
                     (coalesce(group_id, 0) + coalesce(offer_id, 0) +
              coalesce(curriculum_unit_id, 0) + coalesce(course_id, 0)) as entity_id,
                    --parents do tipo offer
                     CASE
                       WHEN group_id is not null THEN (
                         select coalesce(t.id,0)
                         from
                           groups g
                           left join allocation_tags t on t.offer_id = g.offer_id
                         where
                           g.id = root.group_id
                       )
                       ELSE (select 0)
                     END as offer_parent_tag_id,

                     --parents do tipo curriculum unit
                     CASE
                       WHEN group_id is not null THEN (
                         select coalesce(t.id,0)
                         from
                           groups g
                           left join offers o on g.offer_id = o.id
                           left join allocation_tags t on t.curriculum_unit_id = o.curriculum_unit_id
                         where
                           g.id = root.group_id
                       )
                       WHEN offer_id is not null THEN (
                         select coalesce(t.id,0)
                         from
                           offers o
                           left join allocation_tags t on t.curriculum_unit_id = o.curriculum_unit_id
                         where
                           o.id = root.offer_id
                       )
                       ELSE (select 0)
                     END as curriculum_unit_parent_tag_id,

                     --parents do tipo course
                     CASE
                       WHEN group_id is not null THEN (
                         select coalesce(t.id,0)
                         from
                           groups g
                           left join offers o on g.offer_id = o.id
                           left join allocation_tags t on t.course_id = o.course_id
                         where
                           g.id = root.group_id
                       )
                       WHEN offer_id is not null THEN (
                         select coalesce(t.id,0)
                         from
                           offers o
                           left join allocation_tags t on t.course_id = o.course_id
                         where
                           o.id = root.offer_id
                       )
                       ELSE (select 0)
                     END as course_parent_tag_id
              from
                     allocation_tags root
              order by entity_type, allocation_tag_id) as hierarchy
              on
                (al.allocation_tag_id = hierarchy.allocation_tag_id) or
                (al.allocation_tag_id = hierarchy.offer_parent_tag_id) or
                (al.allocation_tag_id = hierarchy.curriculum_unit_parent_tag_id) or
                (al.allocation_tag_id = hierarchy.course_parent_tag_id)
            where
                #{negative} cast( p.types & '#{profile_flag.to_s(2)}' as boolean) AND
                al.status=#{Allocation_Activated} AND
                (
                  (hierarchy.allocation_tag_id = #{allocation_tag_id}) or
                  (hierarchy.offer_parent_tag_id = #{allocation_tag_id}) or
                  (hierarchy.curriculum_unit_parent_tag_id = #{allocation_tag_id}) or
                  (hierarchy.course_parent_tag_id = #{allocation_tag_id})
                )
           ORDER BY profilename, users.name"

      participants = User.find_by_sql(query)

      return participants
    else
      return nil
    end
  end
end

app/views/curriculum_units/_agenda_portlet.html.haml
#block_schedule.block_small
  .block_title
    %h2
      %i.icon-calendar
      = t(:curriculum_access_agenda)
  .calendar#agenda{:url_for => schedules_path}
  .calendar_events

:javascript
  var dates_with_events = eval(#{@scheduled_events});
  $(function() { showAgenda(dates_with_events); });

app/views/curriculum_units/_discussion_posts_portlet.html.haml
/ Portlet da Unidade Curricular que exibe as postagens dos fóruns ligados a ela mais recentes.
.block_small#forum_portlet
  .block_title
    %h2
      %i.icon-forum
      = t(:curriculum_access_forum)

  .block_content#block_forum
    - if !(@discussion_posts.nil? || @discussion_posts.empty?)
      - @discussion_posts.each do |discussion_post|
        .block_content_line
          %span.block_content_gray
            - if posted_today?(discussion_post.updated_at.to_datetime)
              = l(discussion_post.updated_at, :format => :today)
            - else 
              = l(discussion_post.updated_at, :format => :not_today)
          = link_to discussion_post.user.nick, discussion_posts_path(discussion_post.discussion_id), {:class => "link_content"}
          - clear_content = strip_tags discussion_post.content
          - clear_content = clear_content.rpartition("&")[0] if clear_content.rpartition("&")[2].length < 8 
          - clear_content = slice_content(clear_content, 107) << ' (...)' if clear_content.length > 110
          = raw clear_content
    - else
      .block_content_text= t(:forum_no_messages)

app/views/curriculum_units/_form.html.haml
= javascript_include_tag "edition"

%span.form_requirement= t(:required_fields)
.curriculum_unit_form
  = simple_form_for(@curriculum_unit, html: {id: "curriculum_unit_form"}) do |f| 

    .form-inputs.block_content
      = f.label :curriculum_unit_type
      %span#text_as_label=@curriculum_unit.curriculum_unit_type.description
      = f.association :curriculum_unit_type, as: :hidden, input_html: {value: @curriculum_unit.curriculum_unit_type.id}
      = f.input :name
      = f.input :code
      = f.input :passing_grade, input_html: { min: 0, max: 10, step: 0.5 }
      = f.input :resume 
      = f.input :syllabus
      = f.input :objectives, :class => "btn btn_default"
      = f.input :prerequisites 
      .form-actions.button-align
        = button_tag t(".cancel"), class: "btn btn_default btn_lightbox", type: "button", alt: t(:cancel, scope: [:discussion, :buttons]), id: "cancel"
        = button_tag t(".save"), class: "btn btn_main btn_lightbox", alt: t(:save, scope: [:discussion, :buttons]), type: "button", id: "save"

:javascript

  $(function(){
    $('#save').click(function(){
      $('#curriculum_unit_form').serialize_and_submit({
        complement_success: function(data) {
          var post_code_name = data.code_name;
          var id = data.id;
          var url = "#{curriculum_units_path(type_id: @curriculum_unit.curriculum_unit_type.id, curriculum_unit_id: 'curriculum_unit_param')}";

          // criar método pra poder chamar em todas as listagens
          if ($("#curriculum_unit").is_empty())
            var curriculum_unit_id = '';
          else
            var curriculum_unit_id = $("#curriculum_unit").combobox('value');

          $.get(url.replace('curriculum_unit_param', curriculum_unit_id), function(data) {
            $('.ucs_list').html(data);

            var autocomplete_option = $('option[value='+id+']');

            if (!autocomplete_option.length){
              // cria nova uc na lista
              $("<option value="+id+">"+post_code_name+"</option>").appendTo("#curriculum_unit");
            } else {
              // atualiza a uc alterada na lista do autocomplete
              autocomplete_option.text(post_code_name);
              // se a uc alterada foi a selecionada no autocomplete, alterar o valor do input
              if($("#curriculum_unit").combobox('value') == id)
                $("#autocomplete-input").val(post_code_name);
            }
          });
        }
      });
    });

    $("#cancel").click(function(){
      removeLightBox();
    });
  });

app/views/curriculum_units/_index.html.haml
- tool_name = case @type.id
  - when 3
  - "course"
  - when 4
  - "module"
  - else
  - "curriculum_unit"
- t_tool_name = t(".#{tool_name}")

.block_wrapper
  .block_title
    %h2=t_tool_name
  .block_content_toolbar
    .block_toolbar_left.btn-group
      %a.btn.btn_main{:'data-tooltip' => t(".new_#{tool_name}"), id: "btn_new_curriculum_unit", :type => :button, :"data-link-new" => new_curriculum_unit_path(type_id: @type.id)}
        = content_tag(:i, nil, class: 'icon-plus-3')
    .block_toolbar_right
      = link_to (content_tag(:i, nil, class: 'icon-trash')), "#", class: 'btn delete_curriculum_unit btn_del', :'data-tooltip' => t(".delete", uc_or_module: t_tool_name), :"data-link-delete" => curriculum_unit_path(id: ':id')

  %table.tb_list{:cellpadding => "10", :cellspacing => "0", :width => "100%", :style => "table-layout: fixed"}
    %thead
      %tr.lines
        %th{:width => "12%"}
          %input#all_curriculum_unit{type: "checkbox", :"data-children-names" => "ckb_curriculum_unit"}
          = CurriculumUnit.human_attribute_name(:code)
        %th{:width => "38%"}= CurriculumUnit.human_attribute_name(:name)
        %th{:width => "28%"}= CurriculumUnit.human_attribute_name(:category)
        %th{:width => "12%"}
    %tbody
      - @curriculum_units.each do |curriculum_unit|
        %tr.lines
          %td
            = check_box_tag 'ckb_curriculum_unit', curriculum_unit.id, checked = false, {class: 'selected_curriculum_unit', :"data-curriculum_unit-id" => curriculum_unit.id}
            = curriculum_unit.code
          %td= curriculum_unit.name
          %td{:align => "left"}= curriculum_unit.curriculum_unit_type.description
          %td{:align => "right"}
            = link_to (content_tag(:i, nil, class: 'icon-edit')), "#", class: 'btn edit', :'data-tooltip' => t(".edit", uc_or_module: t_tool_name), :"data-link-edit" => edit_curriculum_unit_path(curriculum_unit), disabled: not(can? :update, curriculum_unit)

:javascript

  function result_error(data) {
    var response = JSON.parse(data.responseText);
    if (typeof(response.alert) != "undefined")
      flash_message(response.alert, 'alert');
  }

  $(function(){
    $('.delete_curriculum_unit').attr("disabled", true);

    $("#btn_new_curriculum_unit").click(function(){
      showLightBoxURL($(this).data('link-new'), 540, 605, true, $(this).data('tooltip'));
    });

    $('.edit:not([disabled])').click(function(){
      showLightBoxURL($(this).data('link-edit'), 540, 605, true, $(this).data('tooltip'));
    });

    $('.delete_curriculum_unit').click(function(){
      if ($(this).attr('disabled') == 'disabled' || !confirm("#{t(:message_confirm)}"))
        return false;

      // tentar melhorar o nice_delete para incluir a delecao de muitas linhas

      var ucs = $("#ckb_curriculum_unit:checked");
      var uc_ids = $.map(ucs, function(n){ return ($(n).val()); });

      if (uc_ids.length) {
        $.delete($(this).data('link-delete').replace(':id', uc_ids), function(data){
          flash_message(data.notice, 'notice');
          ucs.parents('tr').fadeOut().remove();
        }).error(function(data){
          var data = $.parseJSON(data.responseText);
          if (typeof(data.alert) != "undefined")
            flash_message(data.alert, 'alert');
        });
      }

      return false;
    });

    $(".block_toolbar_right span.btn")
      .on('click',function(){
        var check = $(':checkbox', this);
        check.prop('checked', !check[0].checked);
      });

    $('#all_curriculum_unit').nice_checkbox({
      can_enable_elements: true
    });

    
  });

app/views/curriculum_units/_lesson_portlet.html.erb
<div class="block_wrapper">
  <div class="block_title">
    <h2><i class="icon-lesson"></i>&nbsp;<%= t(:curriculum_access_lesson) %></h2>
  </div>
  <div class="block_content" id="block_lessons">
    <% unless @lessons.nil? or @lessons.empty? %>
      <% @lessons.each do |lesson| %>
        <div class="block_content_line <%= 'period_ended' if lesson.closed == 't' %>">
          <% schedule= Schedule.find(lesson.schedule_id) %>
          <% if lesson.schedule.end_date.nil? %>
            <span class="block_content_gray">
              <%= l schedule.start_date, :format => :normal %> - <%= t(:no_end_date, scope: [:lessons, :list]) %>
            </span>
          <% elsif lesson.schedule.end_date >= Date.today or lesson.schedule.end_date < Date.today %>
            <span class="block_content_gray">
              <%= l schedule.start_date, :format => :normal  %> - <%= l schedule.end_date, :format => :normal %>
            </span>
          <% end %>
          <% if (lesson.schedule.end_date.nil?) or (lesson.schedule.end_date >= Date.today) %>
            <a class="link_content" href="javascript:show_lesson('<%= url_for :controller => :lessons, :action => :show, :id => lesson.lesson_id %>')">
              <%= lesson.name %>
            </a>
          <% else %>
            <%=lesson.name%> <%= "(#{t(:lesson_closed_short)})" if lesson.closed == 't' %>
          <% end %>
        </div>
      <% end %>
    <% else %>
      <div class="block_content_spacing block_content_text"><%= t(:lesson_message) %></div>
    <% end %>
  </div>
</div>

app/views/curriculum_units/_message_portlet.html.haml
- message_is_present = (not @messages.nil? and not @messages.empty?)
#block_messages.block_small
  .block_title
    %h2
      %i.icon-mail
      = t(:curriculum_access_message)
      - if message_is_present
        %span.text_alert
          \ [#{@messages.count}] #{t(:curriculum_access_new)}
  #block_messages_content.block_content
    - if message_is_present
      - @messages.each do |message|
        .block_content_line
          %span.block_content_gray
            = l message.send_date, format: ((message.send_date.to_date == Date.today) ? :today : :not_today)
          = link_to message.sent_by.name.truncate(13), message_path(id: message.id, bread: :menu_messages, box: :inbox), {class: 'link_content'}
          = raw message.subject.truncate(63)
    - else
      .block_content_text= t(:message_no_new)
  .block_messages_opt
    = link_to t(:curriculum_access_message_inbox), messages_path(bread: :menu_messages), {class: "link_content_gray"}
    \ |
    = link_to t(:curriculum_access_message_new), new_message_path(bread: :menu_messages), {class: "link_content_gray"}

app/views/curriculum_units/_select_curriculum_unit.html.haml
= select_tag :curriculum_unit, options_from_collection_for_select(@curriculum_units, 'id', 'code_name'), include_blank: true

app/views/curriculum_units/edit.html.erb
<%= render 'form' %>

app/views/curriculum_units/home.html.haml
%div
  .block_wrapper
    .block_title
      .block_left
        %h2= t(:curriculum_access_curriculum_unit)
      .block_right
        %h2= t(:curriculum_unit_responsible)
    .block_content
      .block_left
        = @curriculum_unit.resume
      .block_right
        - if @responsible
          - @responsible.each do |resp|
            = [resp.name, " (", resp.profile_name, ") "].join
            / %span= link_to (image_tag "icon_message.png", alt: t(:icon_send_email))
            %br

  = render "lesson_portlet"

  .block_wrapper.block_wrapper_small
    = render "message_portlet"
    = render "discussion_posts_portlet"
    = render "agenda_portlet"

app/views/curriculum_units/informations.html.haml
.block_wrapper
  
  .block_title
    %h2
      %i.icon-docs
      = t(:curriculum_unit_information_title)

  %table.tb_list{:border => "0", :cellpadding => "0", :cellspacing => "0", :width => "100%"}
    %tbody
      %tr.lines
        %td{:style => "width: 20%;"}= t(:syllabus) 
        %td= @curriculum_unit.syllabus 
      %tr.lines
        %td= t(:objectives)
        %td= @curriculum_unit.objectives
      %tr.lines
        %td= t(:prerequisites) 
        %td= @curriculum_unit.prerequisites 
      %tr.lines
        %td= t(:resume) 
        %td= @curriculum_unit.resume 
      - unless @offer.nil?
        %tr.lines
          %td= t(:semester_date) 
          %td
            =l @offer.start_date
            = "-"
            =l @offer.end_date 
      %tr.lines
        %td= t(:passing_grade) 
        %td= @curriculum_unit.passing_grade 
      %tr.lines
        %td= t(:curriculum_unit_responsible) 
        %td
          - if @responsible
            - @responsible.each do |resp|
              =resp.name + ' (' + resp.profile_name + ') '
              %span= link_to(content_tag(:i, nil, :class=>'icon-mail'), nil, :class=>"nodecoration")
              %br

app/views/curriculum_units/new.html.erb
<%= render 'form' %>	

app/views/curriculum_units/participants.html.erb
<div class="block_wrapper">
  <div class="block_title">
    <h2><%=t(:curriculum_unit_responsible)%></h2>
  </div>
  <div class="block_content block_content_overflow">
  <% if @responsible %>

    <% if @responsible.length == 0 %>
      <div class="participants_list_none"><%= t(:participants_none)%></div>
    <% end %>

    <% @responsible.each do |resp| %>
      <div class="participants_list_item">
        <% if resp.photo_file_name %>
          <%=image_tag resp.photo.url(:medium), :alt => t(:mysolar_alt_img_user) + ' ' + resp.name %>
        <% else %>
          <%=image_tag 'no_image.png', :alt => t(:mysolar_alt_img_user) + ' ' + resp.name %>
        <% end %>

        <div class="participant_name" title="<%=resp.name%>">
          <% if resp.name.length > 20 %>
            <%=resp.name.slice(0..19) + '...'%>
          <% else %>
            <%=resp.name%>
          <% end %>
        </div>
        <div class="participant_role">
          <%= raw("(#{resp.profile_name})") %>
        </div>
      </div>
    <% end %>
  <% else %>
    <div class="participants_list_none"><%= t(:participants_none)%></div>
  <% end %>
  </div>
</div>

<div class="block_wrapper">
  <div class="block_title">
    <h2><%=t(:curriculum_unit_participants)%></h2>
  </div>
  <div class="block_content block_content_overflow">
  <% if @participants %>
    <% if @participants.length == 0 %>
      <div class="participants_list_none"><%= t(:participants_none)%></div>
    <% end %>

    <% @participants.each do |part| %>
      <div class="participants_list_item">
        <% unless part.photo_file_name.nil? %>
          <%=image_tag part.photo.url(:medium), :alt => t(:mysolar_alt_img_user) + ' ' + part.name %>
        <% else %>
          <%=image_tag 'no_image.png', :alt => t(:mysolar_alt_img_user) + ' ' + part.name %>
        <% end %>

        <div class="participant_name" title="<%=part.name%>">
          <% if part.name.length > 20 %>
            <%=part.name.slice(0..19) + '...'%>
          <% else %>
            <%=part.name%>
          <% end %>
        </div>

        <div class="participant_role">
          <% if part.profile_id.to_s != @student_profile.to_s %>
            <%= raw("(#{part.profile_name})") %>
          <% else %>
            <br/>
          <% end %>
        </div>
      </div>
    <% end %>

  <% else %>
    <div class="participants_list_none"><%= t(:participants_none)%></div>
  <% end %>
  </div>
</div>