config/routes.rb
Solar::Application.routes.draw do 

  devise_for :users, :path_names => {:sign_up => :register}

  devise_scope :user do
    get  :login, to: "devise/sessions#new"
    post :login, to: "devise/sessions#create"
    get  :logout, to: "devise/sessions#destroy"
    get "/", to: "devise/sessions#new"
    resources :sessions, only: [:create]
  end

  ## users/:id/photo
  ## users/edit_photo
  resources :users do
    get :photo, on: :member
    put :update_photo, on: :member
    get :edit_photo, on: :collection
    get :verify_cpf, on: :collection
  end

  resources :social_networks, only: [] do
    collection do
      get :fb_authenticate
      get :fb_feed
      get :fb_logout
      get :fb_post_wall
    end
  end

  ## curriculum_units/:id/participants
  ## curriculum_units/:id/informations
  resources :curriculum_units do
    collection do 
      get :list
      get :mobilis_list
      get :list_informations
      get :list_participants
      get :list_combobox, to: :index, combobox: true, as: :list_combobox
    end
    member do
      get :participants
      get :informations
      get :home
    end
    resources :groups, only: [:index] do
      collection do 
        get :mobilis_list
      end
    end
  end

  ## groups/:id/discussions
  resources :groups, except: [:show] do
    resources :discussions, only: [:index] do
      collection do 
        get :mobilis_list
      end
    end  
    get :list, on: :collection
    get :list_to_edit, to: :list, on: :collection, edition: true
    get :academic_index, on: :collection
    put :unbind, on: :member, to: :change_tool, type: "unbind"
    put :remove, on: :member, to: :change_tool, type: "remove"
    put :add, on: :collection, to: :change_tool, type: "add"
  end

  ## discussions/:id/posts
  resources :discussions do
    get :list, on: :collection
    resources :posts, except: [:show, :new, :edit] do
      collection do
        get "user/:user_id", to: :show, as: :user
        get ":type/:date(/order/:order(/limit/:limit))", to: :index, defaults: {display_mode: 'list'} # :types => [:news, :history]; :order => [:asc, :desc]
      end
    end
  end

  ## posts/:id/post_files
  resources :posts, only: [:index] do
    resources :post_files, only: [:new, :create, :destroy, :download] do
      get :download, on: :member
    end
  end

  ## allocations/enrollments
  resources :allocations, except: [:new] do
    collection do
      get :designates
      get :enrollments, action: :index
      get :search_users
      post :create_designation
    end
    member do
      delete :cancel, action: :destroy
      delete :cancel_request, action: :destroy, defaults: {type: 'request'}

      post :reactivate
      put :deactivate
      put :activate
    end
  end

  resources :semesters, except: [:show] do
    get :list_combobox, to: :index, combobox: true, as: :list_combobox, on: :collection
    resources :offers, only: [:index, :new]
  end

  resources :offers, except: [:new] do
    post :deactivate_groups, on: :member
    get :list, on: :collection
  end

  resources :scores, only: [:index, :show] do
    collection do 
    get "student/:student_id", action: :show, as: :student
    get :amount_history_access
    get "history_access/:id", action: :history_access
    end
    get :history_access, on: :member
  end

  resources :enrollments, only: :index
  resources :courses do 
    get :list_combobox, to: :index, combobox: true, as: :list_combobox, on: :collection
  end

  resources :editions, only: [] do
    collection do
      get :items
      get :academic
      get :content
      get "academic/:curriculum_unit_type_id/courses", to: "editions#courses", as: :academic_courses
      get "academic/:curriculum_unit_type_id/curriculum_units", to: "editions#curriculum_units", as: :academic_uc
      get "academic/:curriculum_unit_type_id/semesters", to: "editions#semesters", as: :academic_semesters
      get "academic/:curriculum_unit_type_id/groups", to: "editions#groups", as: :academic_groups
    end
  end

  resources :lessons do
    member do
      put "change_status/:status", to: :change_status, as: :change_status
      get :header, to: :show_header
      get :content, to: :show_content
      put "order/:change_id", action: :order, as: :change_order
      put :change_module
    end
    collection do
      get :list, action: :list
      get :download_files
      get :verify_download
    end
    resources :files, controller: :lesson_files, except: [:index, :show, :update, :create] do
      collection do
        get "extract/:file", to: :extract_files, as: :extract, constraints: { file: /.*/ }
        post :folder, to: :new, defaults: {type: 'folder'}, as: :new_folder
        post :file, to: :new, defaults: {type: 'file'}, as: :new_file
        put :rename_node, to: :edit, defaults: {type: 'rename'}
        put :move_nodes, to: :edit, defaults: {type: 'move'}
        put :upload_files, to: :new, defaults: {type: 'upload'}, as: :upload
        put :define_initial_file, to: :edit, defaults: {type: 'initial_file'}, as: :initial_file
        delete :remove_node, to: :destroy
      end
    end
  end
  get :lesson_files, to: "lesson_files#index", as: :lesson_files
 
  mount Ckeditor::Engine => "/ckeditor"

  resources :assignments do
    collection do
      get :student
      get :professor

      get :download_files
      get :send_public_files_page

      post :upload_file
      delete :delete_file
    end
    member do
      get :information
      get :import_groups_page
      post :evaluate
      post :send_comment
      post :manage_groups
      post :import_groups
      delete :remove_comment
    end
  end

  resources :chat_rooms

  resources :schedules, only: [:index] do
    get :list, on: :collection
  end

  resources :messages, except: [:destroy, :update] do
    member do
      put ":box/:new_status", to: "messages#update", as: :change_status, constraints: {box: /(inbox)|(outbox)|(trashbox)/, new_status: /(read)|(unread)|(trash)|(restore)/}
    end

    collection do
      get :index, box: "inbox"
      get :inbox, action: :index, box: "inbox", as: :inbox
      get :outbox, action: :index, box: "outbox", as: :outbox
      get :trashbox, action: :index, box: "trashbox", as: :trashbox

      post :ajax_get_contacts
      post :send_message

      get "download/file/:file_id", to: "messages#download_files", as: :download_file
    end
  end

  resources :pages, only: [:index] do
    # get :team, on: :collection
  end

  resources :lesson_modules, except: [:index, :show]

  # resources :tabs, only: [:show, :create, :destroy]
  get :activate_tab, to: "tabs#show", as: :activate_tab
  get :add_tab, to: "tabs#create", as: :add_tab
  get :close_tab, to: "tabs#destroy", as: :close_tab

  get :home, to: "users#mysolar", as: :home
  get :user_root, to: 'users#mysolar'

  resources :support_material_files do
    get :download, on: :member
    collection do
      get :list
      get "at/:allocation_tag_id/download", to: :download, type: :all, as: :download_all
      get "at/:allocation_tag_id/folder/:folder/download", to: :download, type: :folder, as: :download_folder
      get "at/download", to: :download, type: :all, as: :download_all
      get "at/folder/:folder/download", to: :download, type: :folder, as: :download_folder
    end
  end

  get "bibliography/list", to: "bibliography#list"

  get "/media/lessons/:id/:file.:extension", to: "access_control#lesson", index: true
  get "/media/lessons/:id/:folder/*path", to: "access_control#lesson", index: false

  get "/media/users/:user_id/photos/:style.:extension", to: "access_control#users"

  get "/media/messages/:file.:extension", to: "access_control#message"
  get "/media/assignment/sent_assignment_files/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/comments/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/public_area/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/enunciation/:file.:extension", to: "access_control#assignment"

  # IM
  resources :instant_messages, only: [] do
    collection do
      get :register_user
      get :prebind
    end
  end

  root to: 'devise/sessions#new'

  # match ':controller(/:action(/:id(.:format)))'
end

app/models/group.rb
class Group < ActiveRecord::Base

  include Taggable

  belongs_to :offer

  has_one :curriculum_unit, through: :offer
  has_one :course, through: :offer

  has_many :academic_allocations, through: :allocation_tag

  validates :code, :offer_id, presence: true

  # modulo default da turma
  after_create :set_default_lesson_module

  def assignments
    Assignment.joins(:groups).where(groups: {id: id})
  end

  def code_semester
    "#{code} - #{offer.semester.name}"
  end

  def self.find_all_by_curriculum_unit_id_and_user_id(curriculum_unit_id, user_id)
    Group.joins(offer: [:semester]).where(
      offers: {curriculum_unit_id: curriculum_unit_id}, 
      groups: {id: User.find(user_id).groups}).order('semesters.name DESC, groups.code ASC')
  end

  def has_any_lower_association?
    false
  end

  def set_default_lesson_module
    create_default_lesson_module(I18n.t(:general_of_group, scope: :lesson_modules))
  end

  # Recupera os participantes com perfil de estudante
  def students_participants
    allocations.joins(:profile).where("cast( profiles.types & '#{Profile_Type_Student}' as boolean)").where(status: Allocation_Activated).uniq
  end

end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController

  layout false, except: [:index]

  # Mobilis
  def index
    @groups = current_user.groups

    if params.include?(:curriculum_unit_id)
      ucs_groups = CurriculumUnit.find(params[:curriculum_unit_id]).groups
      @groups = ucs_groups.select {|g| (ucs_groups.map(&:id) & @groups.map(&:id)).include?(g.id) }
    end

    respond_to do |format|
      format.html
      format.xml  { render :xml => @groups.map {|g| {id: g.id, code: g.code, semester: g.offer.semester.name} } }
      format.json  { render :json => @groups.map {|g| {id: g.id, code: g.code, semester: g.offer.semester.name} } }
    end
  end

  # SolarMobilis
  # GET /groups/listando.json
  def mobilis_list
     @groups = current_user.groups
    
    if params.include?(:curriculum_unit_id)      
      @groups = CurriculumUnit.find(params[:curriculum_unit_id]).groups.where(id: @groups)
    end

    respond_to do |format|
      format.json { render json: { groups: @groups.map {|g| {id: g.id, code: g.code, semester: g.offer.semester.name} } } }
    end
  end

  # Edicao
  def list
    @offer = Offer.find_by_curriculum_unit_id_and_semester_id_and_course_id(params[:curriculum_unit_id], params[:semester_id], params[:course_id])

    begin
      authorize! :list, Group, on: [@offer.allocation_tag.id]

      @groups = @offer.groups.order("code")
      render partial: 'groups_checkboxes', locals: { groups: @groups } if params[:checkbox]
    rescue CanCan::AccessDenied
      render json: {success: false, alert: t(:no_permission)}, status: :unauthorized
    end
  end

  def new
    authorize! :create, Group
    offer  = Offer.find_by_curriculum_unit_id_and_semester_id_and_course_id(params[:curriculum_unit_id], params[:semester_id], params[:course_id])
    @group = Group.new offer_id: offer.try(:id)
  end

  def edit
    authorize! :update, Group
    @group = Group.find(params[:id])
  end

  def create
    params[:group][:user_id] = current_user.id
    @group = Group.new(params[:group])
    authorize! :create, Group, on: [@group.offer.allocation_tag.id]

    if @group.save
      render json: {success: true, notice: t(:created, scope: [:groups, :success])}
    else
      render :new
    end
  end

  def update
    @group = Group.where(id: params[:id].split(","))
    authorize! :update, Group, on: [@group.first.offer.allocation_tag.id]

    if params[:multiple]
      @group.update_all(status: params[:status])
      render json: {success: true, notice: t(:updated, scope: [:groups, :success])}
    else
      @group = @group.first
      if @group.update_attributes(params[:group])
        render json: {success: true, notice: t(:updated, scope: [:groups, :success])}
      else
        render :edit
      end
    end
  end

  def destroy
    @group = Group.where(id: params[:id].split(","))
    authorize! :destroy, Group, on: [@group.first.offer.allocation_tag.id]

    Group.transaction do 
      begin
        @group.each do |group|
          raise "erro" unless group.destroy
        end
        render json: {success: true, notice: t(:deleted, scope: [:groups, :success])}
      rescue
        render json: {success: false, alert: t(:deleted, scope: [:groups, :error])}, status: :unprocessable_entity
      end
    end
  end

  # desvincular/remover/adicionar turmas para determinada ferramenta
  def change_tool

    begin 

      if params[:type] == "add"
        groups = Group.where(id: params[:id].split(","))
        AcademicAllocation.transaction do 
          AcademicAllocation.create! groups.map {|group| {allocation_tag_id: group.allocation_tag.id, academic_tool_id: params[:tool_id], academic_tool_type: params[:tool_type]}}
        end
      else
        group = Group.find(params[:id])
        academic_allocation = AcademicAllocation.where(allocation_tag_id: group.allocation_tag.id, academic_tool_type: params[:tool_type], academic_tool_id: params[:tool_id]).first
        
        tool_model = params[:tool_type].constantize
        tool = tool_model.find(params[:tool_id])

        unless tool.groups.size == 1 # se não for a única turma
          case params[:type]
            when "unbind" # desvincular uma turma
              new_tool = tool_model.create(tool.attributes)
              academic_allocation.update_attribute(:academic_tool_id, new_tool.id)
              # se a ferramenta possuir um schedule, cria um igual para a nova
              new_tool.update_attribute(:schedule_id, Schedule.create(tool.schedule.attributes).id) if tool.respond_to?(:schedule) 
            when "remove" # remover uma turma
              academic_allocation.destroy
            else
              raise "option_not_found"
          end
        else # se for a única turma
          raise "last_group"
        end
      end

      render json: {success: true, notice: t(".#{params[:type]}", scope: [:groups, :success])}
    rescue ActiveRecord::RecordNotSaved
      render json: {success: false, alert: t(".academic_allocation_already_exists", scope: [:groups, :error])}, status: :unprocessable_entity
    rescue Exception => error
      error_message = t(".#{error.message}", scope: [:groups, :error]) || t(".tool_change", scope: [:groups, :error])
      render json: {success: false, alert: error_message}, status: :unprocessable_entity
    end
    
  end

end

app/views/groups/_form.html.haml
.new_group.block_content
  = simple_form_for @group, html: {id: 'group_form'} do |f|
    .form-inputs.block_content
      = f.input :offer_id, as: :hidden, input_html: {value: @group.offer.id}

      %div
        = f.label t(:course)
        = @group.offer.course.name
      %div
        = f.label t(:curriculum_unit)
        = @group.offer.curriculum_unit.name
      %div
        = f.label t(:semester)
        = @group.offer.semester.name

      = f.input :code

      .right_buttons
        = button_tag t(:cancel), :class => "btn btn_default btn_lightbox", :type => "button", onclick: "javascript:removeLightBox();"
        = button_tag t(:save), :class => "btn btn_main btn_lightbox", :type => "button", :id => "save"

:javascript

  $(function(){

    $("#save").click(function(){
      $('form#group_form').serialize_and_submit({
        complement_success: function(data) {
          var url = "#{list_groups_path(type: @group.offer.curriculum_unit.curriculum_unit_type.id, curriculum_unit_id: 'curriculum_unit_param', course_id: 'course_param', semester_id: 'semester_param')}".replace('curriculum_unit_param', $('#curriculum_unit').combobox('value')).replace('course_param', $('#course').combobox('value')).replace('semester_param', $('#semester').combobox('value'));

          $.get(url, function(data) {
            $('.groups_list').html(data);
          });
        }
      });
    });

  });

app/views/groups/_groups_checkboxes.html.haml
= hidden_field_tag :all_groups_ids, @groups.map(&:id)

= form_for :group do |f|
  %span.select_all_box
    = check_box_tag :all, :all, false, {:"data-children-names" => "group[group_id][]"}
    = label_tag :all, t(".select_all")
  .no_groups= t(".no_groups")
  %div
    = f.collection_check_boxes :group_id, @groups, :id, :code

:javascript

  $(function(){
    $("#all").nice_checkbox();

    if($('[name="group[group_id][]"]').length ==1){
    	$('.select_all_box').remove(); 
    	$(".no_groups").show(); 
    }

  });

app/views/groups/_groups_tags.html.haml
.groups_tags
  %span.title= label_tag t(".groups")
  - groups.each do |group|
    %span.collection_check_boxes
      = group.code
      - unless groups.size == 1
        = content_tag(:i, nil, class: "icon icon-cross change_tool_group", :"data-dropdown" => ".change_tool_dropdown_#{group.id}_#{tool_id}")
        %div{id: "dropdown", class: "dropdown dropdown-tip change_tool_dropdown_#{group.id}_#{tool_id}"}
          %ul.dropdown-menu
            %li= link_to t(".unbind"), '#', class: 'unbind', :"data-link" => unbind_group_path(id: group.id, tool_id: tool_id, tool_type: "ChatRoom")
            %li= link_to t(".remove"), '#', class: 'remove', :"data-link" => remove_group_path(id: group.id, tool_id: tool_id, tool_type: "ChatRoom")

  - new_groups = (all_groups - groups).in_groups(2, false)
  - unless new_groups.first.empty?
    %span.new_groups
      = content_tag(:i, nil, class: "icon icon-plus-3 add_group", :"data-dropdown" => ".add_group_dropdown_#{tool_id}")
      %div{id: "dropdown", class: "dropdown dropdown-tip add_group_dropdown_#{tool_id}"}
        = form_for :group do |f|
          - new_groups.each do |new_group|
            .no_tags= f.collection_check_boxes :new_group_id, new_group, :id, :code
          = button_tag t(".add"), class: "btn btn_add_group", :"data-link" => add_groups_path(id: 'param_id', tool_id: tool_id, tool_type: "ChatRoom"), type: :button
          = button_tag t(".cancel"), class: "btn btn_cancel_add_group", type: :button

app/views/groups/_partial_group_list.html.haml
= javascript_include_tag "tooltip"

- unless groups.nil? or groups.empty?
  %table.tb_list
    %thead
      %tr.lines
        %th= t(".code")
        %th{style: "width: 10%"}= t(".activation")
    %tbody
      - groups.each do |group|
        %tr.lines
          %td
            = check_box_tag :ckb_group, group.id, false, {class: "ckb_group"}
            = group.code
          %td{style: "text-align: center"}= link_to (image_tag "#{(group.status) ? 'released' : 'rejected'}.png"), "#", class: "change_status_group", :'data-tooltip' => (group.status ?  t(".enabled") :  t(".disabled")), :"data-link-status" => group_path(id: group.id, status: (not group.status), multiple: true), disabled: not(can? :update, Group)

app/views/groups/edit.html.haml
= render 'form'

app/views/groups/index.html.haml
.block_title= t(:group)
.block_wrapper
  %table.tb_list
    %thead
      %tr.lines
        %th= t(:group)
        %th= t(:curriculum_unit)
        %th= t(:course)
        %th= t(:offer)
    %tbody
      - unless @groups.nil? or @groups.empty?
        - @groups.each do |group|
          %tr.lines
            %td= group.code
            %td= group.curriculum_unit.name
            %td= group.course.name
            %td= group.offer.semester.name

app/views/groups/list.html.haml
= javascript_include_tag "tooltip"

.block_wrapper.list_groups{:"data-link" => list_groups_path(semester_id: 'semester_param', course_id: 'course_param', curriculum_unit_id: 'curriculum_unit_param')}

  .block_title
    %h2= t(:groups, scope: [:editions, :academic])
  .block_content_toolbar
    .block_toolbar_left.btn-group
      %a.btn.btn_main{:'data-tooltip' => t(".new"), id: "btn_new_group", :type => :button, :"data-link-new-group" => new_group_path(semester_id: 'semester_param', course_id: 'course_param', curriculum_unit_id: 'curriculum_unit_param'), :'data-tooltip' => t(".new")}
        = content_tag(:i, nil, class: 'icon-plus-3')
    .block_toolbar_right
      = link_to (content_tag(:i, nil, class: 'icon-checkbox-unchecked')), "#", id: 'all_groups', class: 'btn', :'data-tooltip' => t(".all"), :"data-children-names" => "ckb_group", disabled: (@groups.empty?)
      = link_to ((content_tag(:i, nil, class: 'icon-edit'))), "#", class: 'btn btn_edit', :'data-tooltip' => t(".edit"), :"data-link-edit-group" => edit_group_path(id: ':id')
      = link_to (content_tag(:i, nil, class: 'icon-cross')), "#", class: 'btn disable_group', :'data-tooltip' => t(".disable"), :"data-link-status" => group_path(id: ':id', status: false, multiple: true)
      = link_to (content_tag(:i, nil, class: 'icon-checkmark')), "#", class: 'btn enable_group', :'data-tooltip' => t(".enable"), :"data-link-status" => group_path(id: ':id', status: true, multiple: true)
      = link_to (content_tag(:i, nil, class: 'icon-trash')), "#", class: 'btn btn_del', :'data-tooltip' => t(".delete"), :"data-link-delete" => group_path(id: ':id')

  - part1, part2 = @groups.in_groups(2, false)

  - if @groups.count
    .block_content.groups
      .block_left
        = render "partial_group_list", groups: part1
      .block_right
        = render "partial_group_list", groups: part2
  - else
    .block_content.block_content_text= t(".none")

= javascript_include_tag "groups"
  

app/views/groups/new.html.haml
= render 'form'