config/routes.rb
Solar::Application.routes.draw do 

  devise_for :users, :path_names => {:sign_up => :register}

  devise_scope :user do
    get  :login, to: "devise/sessions#new"
    post :login, to: "devise/sessions#create"
    get  :logout, to: "devise/sessions#destroy"
    get "/", to: "devise/sessions#new"
    resources :sessions, only: [:create]
  end

  ## users/:id/photo
  ## users/edit_photo
  resources :users do
    get :photo, on: :member
    put :update_photo, on: :member
    get :edit_photo, on: :collection
    get :verify_cpf, on: :collection
  end

  resources :social_networks, only: [] do
    collection do
      get :fb_authenticate
      get :fb_feed
      get :fb_logout
      get :fb_post_wall
    end
  end

  ## curriculum_units/:id/participants
  ## curriculum_units/:id/informations
  resources :curriculum_units do
    collection do 
      get :list
      get :mobilis_list
      get :list_informations
      get :list_participants
      get :list_combobox, to: :index, combobox: true, as: :list_combobox
    end
    member do
      get :participants
      get :informations
      get :home
    end
    resources :groups, only: [:index] do
      collection do 
        get :mobilis_list
      end
    end
  end

  ## groups/:id/discussions
  resources :groups, except: [:show] do
    resources :discussions, only: [:index] do
      collection do 
        get :mobilis_list
      end
    end  
    get :list, on: :collection
    get :list_to_edit, to: :list, on: :collection, edition: true
    get :academic_index, on: :collection
    put :unbind, on: :member, to: :change_tool, type: "unbind"
    put :remove, on: :member, to: :change_tool, type: "remove"
    put :add, on: :collection, to: :change_tool, type: "add"
  end

  ## discussions/:id/posts
  resources :discussions do
    get :list, on: :collection
    resources :posts, except: [:show, :new, :edit] do
      collection do
        get "user/:user_id", to: :show, as: :user
        get ":type/:date(/order/:order(/limit/:limit))", to: :index, defaults: {display_mode: 'list'} # :types => [:news, :history]; :order => [:asc, :desc]
      end
    end
  end

  ## posts/:id/post_files
  resources :posts, only: [:index] do
    resources :post_files, only: [:new, :create, :destroy, :download] do
      get :download, on: :member
    end
  end

  ## allocations/enrollments
  resources :allocations, except: [:new] do
    collection do
      get :designates
      get :enrollments, action: :index
      get :search_users
      post :create_designation
    end
    member do
      delete :cancel, action: :destroy
      delete :cancel_request, action: :destroy, defaults: {type: 'request'}

      post :reactivate
      put :deactivate
      put :activate
    end
  end

  resources :semesters, except: [:show] do
    get :list_combobox, to: :index, combobox: true, as: :list_combobox, on: :collection
    resources :offers, only: [:index, :new]
  end

  resources :offers, except: [:new] do
    post :deactivate_groups, on: :member
    get :list, on: :collection
  end

  resources :scores, only: [:index, :show] do
    collection do 
    get "student/:student_id", action: :show, as: :student
    get :amount_history_access
    get "history_access/:id", action: :history_access
    end
    get :history_access, on: :member
  end

  resources :enrollments, only: :index
  resources :courses do 
    get :list_combobox, to: :index, combobox: true, as: :list_combobox, on: :collection
  end

  resources :editions, only: [] do
    collection do
      get :items
      get :academic
      get :content
      get "academic/:curriculum_unit_type_id/courses", to: "editions#courses", as: :academic_courses
      get "academic/:curriculum_unit_type_id/curriculum_units", to: "editions#curriculum_units", as: :academic_uc
      get "academic/:curriculum_unit_type_id/semesters", to: "editions#semesters", as: :academic_semesters
      get "academic/:curriculum_unit_type_id/groups", to: "editions#groups", as: :academic_groups
    end
  end

  resources :lessons do
    member do
      put "change_status/:status", to: :change_status, as: :change_status
      get :header, to: :show_header
      get :content, to: :show_content
      put "order/:change_id", action: :order, as: :change_order
      put :change_module
    end
    collection do
      get :list, action: :list
      get :download_files
      get :verify_download
    end
    resources :files, controller: :lesson_files, except: [:index, :show, :update, :create] do
      collection do
        get "extract/:file", to: :extract_files, as: :extract, constraints: { file: /.*/ }
        post :folder, to: :new, defaults: {type: 'folder'}, as: :new_folder
        post :file, to: :new, defaults: {type: 'file'}, as: :new_file
        put :rename_node, to: :edit, defaults: {type: 'rename'}
        put :move_nodes, to: :edit, defaults: {type: 'move'}
        put :upload_files, to: :new, defaults: {type: 'upload'}, as: :upload
        put :define_initial_file, to: :edit, defaults: {type: 'initial_file'}, as: :initial_file
        delete :remove_node, to: :destroy
      end
    end
  end
  get :lesson_files, to: "lesson_files#index", as: :lesson_files
 
  mount Ckeditor::Engine => "/ckeditor"

  resources :assignments do
    collection do
      get :student
      get :professor

      get :download_files
      get :send_public_files_page

      post :upload_file
      delete :delete_file
    end
    member do
      get :information
      get :import_groups_page
      post :evaluate
      post :send_comment
      post :manage_groups
      post :import_groups
      delete :remove_comment
    end
  end

  resources :chat_rooms

  resources :schedules, only: [:index] do
    get :list, on: :collection
  end

  resources :messages, except: [:destroy, :update] do
    member do
      put ":box/:new_status", to: "messages#update", as: :change_status, constraints: {box: /(inbox)|(outbox)|(trashbox)/, new_status: /(read)|(unread)|(trash)|(restore)/}
    end

    collection do
      get :index, box: "inbox"
      get :inbox, action: :index, box: "inbox", as: :inbox
      get :outbox, action: :index, box: "outbox", as: :outbox
      get :trashbox, action: :index, box: "trashbox", as: :trashbox

      post :ajax_get_contacts
      post :send_message

      get "download/file/:file_id", to: "messages#download_files", as: :download_file
    end
  end

  resources :pages, only: [:index] do
    # get :team, on: :collection
  end

  resources :lesson_modules, except: [:index, :show]

  # resources :tabs, only: [:show, :create, :destroy]
  get :activate_tab, to: "tabs#show", as: :activate_tab
  get :add_tab, to: "tabs#create", as: :add_tab
  get :close_tab, to: "tabs#destroy", as: :close_tab

  get :home, to: "users#mysolar", as: :home
  get :user_root, to: 'users#mysolar'

  resources :support_material_files do
    get :download, on: :member
    collection do
      get :list
      get "at/:allocation_tag_id/download", to: :download, type: :all, as: :download_all
      get "at/:allocation_tag_id/folder/:folder/download", to: :download, type: :folder, as: :download_folder
      get "at/download", to: :download, type: :all, as: :download_all
      get "at/folder/:folder/download", to: :download, type: :folder, as: :download_folder
    end
  end

  get "bibliography/list", to: "bibliography#list"

  get "/media/lessons/:id/:file.:extension", to: "access_control#lesson", index: true
  get "/media/lessons/:id/:folder/*path", to: "access_control#lesson", index: false

  get "/media/users/:user_id/photos/:style.:extension", to: "access_control#users"

  get "/media/messages/:file.:extension", to: "access_control#message"
  get "/media/assignment/sent_assignment_files/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/comments/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/public_area/:file.:extension", to: "access_control#assignment"
  get "/media/assignment/enunciation/:file.:extension", to: "access_control#assignment"

  # IM
  resources :instant_messages, only: [] do
    collection do
      get :register_user
      get :prebind
    end
  end

  root to: 'devise/sessions#new'

  # match ':controller(/:action(/:id(.:format)))'
end

app/models/support_material_file.rb
class SupportMaterialFile < ActiveRecord::Base

  GROUP_PERMISSION, OFFER_PERMISSION = true, true
  include ToolsAssociation

  has_one :allocation_tag

  before_save :url_protocol, if: :is_link?

  validates :allocation_tag_id, presence: true
  validates :attachment, presence: true, unless: :is_link?

  validates :url, presence: true, if: :is_link?
  validates_format_of :url, with: /^((http|https|ftp):\/\/)?[a-z0-9]+([\-\.]{1}[a-z0-9]+)*\.[a-z]{2,5}(([0-9]{1,5})?\/.*)?$/ix, if: :is_link?

  has_attached_file :attachment,
    :path => ":rails_root/media/support_material_files/:id_:basename.:extension",
    :url => "/media/support_material_files/:id_:basename.:extension"

  validates_attachment_size :attachment, :less_than => 30.megabyte, :message => ""
  validates_attachment_content_type_in_black_list :attachment

  def url_protocol
    self.url = ['http://', self.url].join if (self.url =~ URI::regexp(["ftp", "http", "https"])).nil? 
  end

  def name
    return "" if url.nil? and attachment_file_name.nil?
    return url unless url.nil?
    return attachment_file_name
  end

  def is_link?
    (material_type == Material_Type_Link)
  end

  def self.find_files(allocation_tag_ids, folder_name = nil)
    in_folder = " AND sm.folder = '#{folder_name}' " unless folder_name.nil?

    query = <<SQL
    SELECT *
      FROM support_material_files sm
     WHERE allocation_tag_id in (#{allocation_tag_ids.join(",")}) #{in_folder}
     ORDER BY sm.folder, sm.attachment_content_type, sm.attachment_file_name
SQL

    SupportMaterialFile.find_by_sql(query);
  end
end

app/models/user.rb
class User < ActiveRecord::Base

  has_one :personal_configuration

  has_many :allocations
  has_many :allocation_tags, :through => :allocations, :uniq => true
  has_many :profiles, :through => :allocations, :uniq => true, conditions: { profiles: {status: true}, allocations: {status: 1} } # allocation.status = Allocation_Activated
  has_many :logs
  has_many :lessons
  has_many :discussion_posts
  has_many :user_messages
  has_many :message_labels
  has_many :assignment_files
  has_many :user_contacts, :class_name => "UserContact", :foreign_key => "user_id"
  has_many :user_contacts, :class_name => "UserContact", :foreign_key => "user_related_id"
  has_many :chat_messages

  after_create :basic_profile_allocation

  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable, :lockable, :timeoutable and :omniauthable, :trackable
  devise :database_authenticatable, :registerable, :validatable,
    :recoverable, :encryptable, :token_authenticatable # autenticacao por token

  before_save :ensure_authentication_token!, :downcase_username

  @has_special_needs

  attr_accessible :username, :email, :email_confirmation, :alternate_email, :password, :password_confirmation, :remember_me, :name, :nick, :birthdate,
    :address, :address_number, :address_complement, :address_neighborhood, :zipcode, :country, :state, :city,
    :telephone, :cell_phone, :institution, :gender, :cpf, :bio, :interests, :music, :movies, :books, :phrase, :site, :photo,
    :special_needs, :is_registered

  attr_accessor :login, :has_special_needs

  email_format = %r{^((?:[_a-z0-9-]+)(\.[_a-z0-9-]+)*@([a-z0-9-]+)(\.[a-zA-Z0-9\-\.]+)*(\.[a-z]{2,4}))?$}i # regex para validacao de email

  validates :cpf, presence: true, uniqueness: true
  validates :name, presence: true, length: { :within => 6..90 }
  validates :nick, presence: true, length: { :within => 3..34 }
  validates :birthdate, presence: true
  validates :username, presence: true, :length => { :within => 3..20 }, :uniqueness => true
  validates :password, presence: true, confirmation: true, unless: Proc.new { |a| a.password.blank? }
  validates :alternate_email, :format => { :with => email_format }
  validates :email, presence: true, confirmation: true, :format => { :with => email_format }, if: Proc.new {|a| a.email_changed? }
  validates :special_needs, presence: true, :if => :has_special_needs?

  validates_length_of :address, :maximum => 99
  validates_length_of :address_neighborhood, :maximum => 49
  validates_length_of :zipcode, :maximum => 9
  validates_length_of :country,:maximum => 90
  validates_length_of :city, :maximum => 90
  validates_length_of :institution, :maximum => 120

  validate :cpf_ok, :unless => :already_cpf_error?

  # paperclip uses: file_name, content_type, file_size e updated_at
  # Configuração do paperclip para upload de fotos
  has_attached_file :photo,
    :styles => { :medium => "72x90#", :small => "25x30#", :forum => "40x40#" },
    :path => ":rails_root/media/:class/:id/photos/:style.:extension",
    :url => "/media/:class/:id/photos/:style.:extension",
    :default_url => "/assets/no_image_:style.png"

  validates_attachment_size :photo, :less_than => 700.kilobyte, :message => " " # Esse :message => " " deve permanecer dessa forma enquanto não descobrirmos como passar a mensagem de forma correta. Se o message for vazio a validação não é feita.
  validates_attachment_content_type :photo,
    :content_type => ['image/jpeg','image/png','image/gif','image/pjpeg'],
    :message => :invalid_type

  default_scope :order => 'name ASC'

  #Garantindo que o cpf nao será salvo com os separadores.
  #  def cpf=(value)
  #    self[:cpf] = value.gsub(/\D/, '')
  #  end

  ##
  # Verifica se o radio_button escolhido na view é verdadeiro ou falso. 
  # Este método também define as necessidades especiais como sendo vazia caso a pessoa tenha selecionado que não as possui
  ##
  def has_special_needs?
    self.special_needs = "" unless @has_special_needs
    @has_special_needs
  end

  ##
  # Verifica se já existe um erro no campo de email ou, caso esteja na edição de usuário, verifica se o email foi alterado.
  # Caso o email não tenha sido alterado, não há necessidade de verificar sua confirmação
  ##
  def already_email_error_or_email_not_changed?
    (errors[:email].any? || !email_changed?)
  end

  def already_cpf_error?
    errors[:cpf].any?
  end

  ##
  # Permite modificação dos dados do usuário sem necessidade de informar a senha - para usuários já logados
  # Define o valor de @has_special_needs na edição de um usuário (update)
  ##
  def update_with_password(params={})
    @has_special_needs = (params[:has_special_needs] == 'true')
    params.delete(:has_special_needs)
    if (params[:password].blank? && params[:current_password].blank? && params[:password_confirmation].blank?)
      params.delete(:current_password)
      self.update_without_password(params)
    else
      super(params)
    end
  end

  ##
  # Este método define os atributos na hora de criar um objeto. Logo, redefine os atributos já existentes e define
  # o valor de @has_special_needs a partir do que é passado da página na criação de um usuário (create)
  ##
  def initialize(attributes = {})
     super(attributes)
     @has_special_needs = (attributes[:has_special_needs] == 'true')
  end

  def cpf_ok
    cpf_verify = Cpf.new(self[:cpf])
    errors.add(:cpf, I18n.t(:new_user_msg_cpf_error)) unless cpf_verify.valido? unless cpf_verify.nil?
  end

  ## Na criação, o usuário recebe o perfil de usuario basico
  def basic_profile_allocation
    new_allocation_user = Allocation.new :profile_id => Profile.find_by_types(Profile_Type_Basic).id, :status => Allocation_Activated, :user_id => self.id
    new_allocation_user.save!
  end

  def ensure_authentication_token!
    reset_authentication_token! if authentication_token.blank? 
  end

  def downcase_username
    self.username = self.username.downcase
  end

  def self.find_for_database_authentication(warden_conditions)
    conditions = warden_conditions.dup
    login = conditions.delete(:login)
    where(conditions).where(["translate(cpf,'.-','') = :value OR lower(username) = :value", { :value => login.strip.downcase }]).first
  end

  def groups(profile_id = nil, status = nil, curriculum_unit_id = nil, curriculum_unit_type_id = nil)
    query = []
    query << "allocations.status = #{status}" unless status.nil?
    query << "allocations.profile_id = #{profile_id}" unless profile_id.nil?
    query << "curriculum_units.id = #{curriculum_unit_id}" unless curriculum_unit_id.nil?
    query << "curriculum_unit_types.id = #{curriculum_unit_type_id}" unless curriculum_unit_type_id.nil?

    allocations.includes(allocation_tag: [group: [offer: [curriculum_unit: :curriculum_unit_type]]]).where(query.join(" AND ")).delete_if {|allocation| allocation.allocation_tag.nil? }.map(&:groups).flatten.compact.uniq
  end

  def profiles_activated(only_id = false)
    profiles = self.profiles.where("allocations.status = ?", Allocation_Activated).uniq
    return (only_id) ? profiles.map(&:id) : profiles
  end

  def profiles_with_access_on(action, controller, allocation_tag_id = nil, only_id = false)
    if allocation_tag_id.nil?
      profiles = self.profiles.
        joins(permissions_resources: :resource).
        where(
          resources: {action: action, controller: controller}).
        order("profiles.id DESC")
    else
      profiles = self.profiles.
        joins(permissions_resources: :resource).
        where(
          allocations: { allocation_tag_id: allocation_tag_id }, 
          resources: {action: action, controller: controller}).
        order("profiles.id DESC")
    end

    return (only_id) ? profiles.map { |p| p.id.to_i } : profiles
  end

  # Retorna os ids das allocations_tags ativadas de um usuário
  def activated_allocation_tag_ids(related = true)
    map = related ? "related" : "id"
    allocation_tags.where(allocations: {status: Allocation_Activated.to_i}).map(&map.to_sym).flatten.uniq
  end

end

app/views/support_material_files/_form.html.haml
.new_support_material_form
  = simple_form_for @support_material, html: {id: 'support_material_form', multipart: true} do |f|
    = hidden_field_tag :allocation_tags_ids, @allocation_tags_ids
    = hidden_field_tag :material_type, @support_material.material_type

    .form-inputs.block_content
      - if @support_material.material_type == Material_Type_Link
        = f.input :url, as: :string, required: true
      - else
        = f.file_field :attachment, as: :file, required: true

      .right_buttons
        = button_tag t(:cancel), :class => "btn btn_default btn_lightbox", :type => "button", onclick: "javascript:removeLightBox();"
        = button_tag t(:save), :class => "btn btn_main btn_lightbox", :type => "button", :id => "save"
    
:javascript

  jQuery(function($){
    $('#support_material_form:first').keypress(function(event) { if (event.keyCode == 13) { event.preventDefault(); } }); // prevenir enter

    $('#save').click(function(){
      $('#support_material_form:first').serialize_and_submit({
        files: true,
        replace_list: $('.list_support_material:last')
      });
    });
  });

app/views/support_material_files/edit.html.haml
= render "form"

app/views/support_material_files/index.html.haml
%div{:style => "margin-bottom:5px"}
  %button#download_all.btn.btn_default{"data-tooltip" => t("support_download_all"), :onclick => "javascript:window.location.href='#{download_all_support_material_files_path(allocation_tag_id: @allocation_tag_ids.join(','), :type => "all")}'", :type => "button", :value => t("support_download_all")}
    %i.icon-archive
- @folders_list.each do |folder_name, folder_content|
  .block_wrapper
    .block_title
      - unless folder_name == 'LINKS'
        %h2.support_material_title= folder_name
        %span.block_actions
          %button#download_folder.btn{"data-tooltip" => t("support_download_folder"), :onclick => "javascript:window.location.href='#{download_folder_support_material_files_path(folder: (folder_name || 'nil'), allocation_tag_id: @allocation_tag_ids.join(','))}'", :type => "button", :value => t("support_download_folder")}
            %i.icon-install
      - else
        %h2= folder_name
    %table.tb_list{:border => "0", :cellpadding => "10", :cellspacing => "0", :width => "100%"}
      %thead
        %tr
          %th= t(:support_material_name)
          %th{:style => "width:80px"}= t(:support_material_size)
          %th{:style => "width:80px"}= t(:support_material_sent_on)
      %tbody
        - folder_content.each do |file|
          %tr.lines
            %td
              - if file['url'] == nil
                = link_to image_tag(icon_attachment(file["attachment_file_name"])), download_support_material_file_path(id: file['id']), {:class => 'file_icon'}
                = link_to file['attachment_file_name'], download_support_material_file_path(id: file['id'])
              - else
                = image_tag 'icon_file_link.png', :alt => ''
                = link_to file['url'], file['url'], :target => '_blank'
            %td
              - if file['url'] == nil
                = format('%.2f KB', file["attachment_file_size"].to_i/1024.0)
            %td
              = l file["attachment_updated_at"].to_date
- if @folders_list.nil? or @folders_list.empty?
  .block_content.block_content_text= t(:itens_not_found)

app/views/support_material_files/list.html.haml
= hidden_field_tag :allocation_tags_ids, @allocation_tags_ids

.list_support_material{:"data-link-list" => list_support_material_files_path(allocation_tags_ids: @allocation_tags_ids)}
  .block_wrapper
    .block_title
      %h2= t(:support_material, scope: [:editions, :items])

    - previous_allocation_tag = nil
    - @allocation_tags.each_with_index do |allocation_tag, idxat|
      /- allocation_tag_path = allocation_tag_path(allocation_tag, @what_was_selected)

      .list_support_materials{id: "list_#{allocation_tag.id}"}
        - unless previous_allocation_tag == idxat
          - previous_allocation_tag = idxat
          /.edition_allocation_tag_path= allocation_tag_path

          .block_content_toolbar
            .block_toolbar_left.btn-group
              %a.btn.btn_main{:href => "#", 'data-dropdown' => "#dropdown_#{allocation_tag.id}"}
                = content_tag(:i, nil, :class=>'icon-plus-3')
                %i.icon-arrow-down-3
              %div{:id=>"dropdown_#{allocation_tag.id}", :class=>"dropdown dropdown-tip"}
                %ul.dropdown-menu
                  %li= link_to t(".new_file"), '#', id: 'new_material_file', :"data-link" => "#{new_support_material_file_path(material_type: Material_Type_File, allocation_tags_ids: [allocation_tag.id])}", :"data-box-title" => t(".new_file")
                  %li= link_to t(".new_link"), '#', id: 'new_material_link', :"data-link" => "#{new_support_material_file_path(material_type: Material_Type_Link, allocation_tags_ids: [allocation_tag.id])}", :"data-box-title" => t(".new_link")

            .block_toolbar_right
              .btn-group
                = link_to (content_tag(:i, nil, :class=>'icon-edit')), "#", class: 'btn btn_edit edit_material', :"data-link-edit" => edit_support_material_file_path(':id', allocation_tags_ids: [allocation_tag.id]), "data-edit-title" => t(".edit_link"), disabled: true
                / = link_to (content_tag(:i, nil, :class=>'icon-install')), "#", onclick: "javascript: alert('em desenvolvimento');", id: 'download_meterial', class: 'btn'
                = link_to (content_tag(:i, nil, :class=>'icon-trash')), "#", class: 'btn btn_del delete_material', :"data-link-delete" => support_material_file_path(':id', allocation_tags_ids: [allocation_tag.id]), disabled: true

          .block_wrapper.support_material
            - materials = allocation_tag.support_material_files
            - unless materials.empty?
              %table.tb_list
                %thead
                  %tr.lines
                    %th{style: 'text-align:center;'}
                    %th{style: 'text-align:left;'}= t(".name")
                    %th{style: 'text-align:center;'}= t(".date")
                    %th{style: 'text-align:center;'}= t(".type")

                %tbody
                  - materials.each do |material|
                    %tr.lines{id: "tr_#{material.id}"}
                      %td{style: 'text-align:center;'}
                        = check_box_tag("c_#{material.id}", material.id, false, {class: "ckb_material", :"data-is-link" => (material.material_type == Material_Type_Link)})
                      %td
                        %div
                          - if material.is_link?
                            %span= image_tag('icon_file_link.png')
                            %span= link_to material.name, material.name, target: '_blank'
                          - else
                            %span= image_tag(icon_attachment(material.name))
                            - if can?(:download, SupportMaterialFile, on: [material.allocation_tag_id]) and File.exists?(material.attachment.path)
                              %span= link_to material.name, download_support_material_file_path(id: material.id, allocation_tag_id: material.allocation_tag_id)
                            - else
                              %span= material.name
                      %td{style: 'text-align:center;'}
                        %div= l(material.attachment_updated_at, format: :normal)
                      %td{style: 'text-align:center;'}
                        %div= (material.is_link?) ? t(".link") : t(".file")
            - else
              .block_content.block_content_text
                = t(".none")

:javascript

  $(function(){
    $('#new_material_link, #new_material_file').click(function() {
      showLightBoxURL($(this).data('link'), 540, 90, true, $(this).data('box-title'));
    });

    $(':checkbox.ckb_material').click(function() {
      var box = $(this).parents("div.list_support_materials");
      var count = $('.ckb_material:checked', box).length;
      $('.btn_edit, .btn_del', box).attr('disabled', !count);

      if (count > 1 || (count == 1 && !$('.ckb_material:checked:first', box).data('is-link'))) { // a edicao vale apenas para uma unica selecao e se for do tipo link
        $('.btn_edit', box).attr('disabled', true);
      }
    });

    $('.edit_material').click(function() {
      if ($(this).attr('disabled') == 'disabled')
        return false;

      var material_ids = $('.ckb_material:checked', $(this).parents("div.list_support_materials")).map(function() { return this.value; }).get();
      if (!(!material_ids.length || material_ids.length > 1 || !$('.ckb_material:checked:first').data('is-link'))) {
        var url_edit = $(this).data('link-edit').replace(':id', material_ids);
        showLightBoxURL(url_edit, 540, 90, true, $(this).data('edit-title'));
      }
      return false;
    });

    $('.delete_material').click(function(){
      if (!confirm("#{t(:message_confirm)}"))
        return false;
      else{
        if(!$(this).hasClass('disabled')){
          var material_ids = jQuery.map($(".ckb_material:checked"), function(n){
            return ($(n).val());
          });

          if ($(material_ids).length != 0){
            $.delete($(this).data('link-delete').replace(':id', material_ids), function(data){
              flash_message(data.notice, 'notice');
              $.get($('.list_support_material').data("link-list"), function(data) {
                $('.list_support_material:last').replaceWith(data);
              });
            }).error(function(){
              flash_message(data.alert, 'alert');
            })
          }else
            return false;
        }
      }
    });

  });

app/views/support_material_files/new.html.haml
= render "form"